-- ============================================================
-- Supabase Schema for Desktop Pet Cloud Co-Parenting (v1)
-- ============================================================
-- 第一版使用 room_code 作为共享房间主键。
-- 第一版采用异步同步，不做实时 Realtime。
--
-- 在 Supabase SQL Editor 中运行：
--   https://supabase.com/dashboard/project/_/sql/new
-- ============================================================

-- ── Pet Rooms ─────────────────────────────────────────────────
create table if not exists public.pet_rooms (
    room_code   text primary key,
    room_name   text not null default '共享宠物房间',
    pet_name    text not null default 'Echo',
    created_at  timestamptz not null default now(),
    updated_at  timestamptz not null default now()
);

-- ── Cloud Pets (one pet per room_code) ─────────────────────────
create table if not exists public.cloud_pets (
    room_code   text primary key references public.pet_rooms(room_code) on delete cascade,
    pet_id      text not null default 'cat',
    pet_name    text not null default 'Echo',
    mood        text not null default 'neutral',
    energy      int not null default 100,
    intimacy    int not null default 50,
    level       int not null default 1,
    exp         int not null default 0,
    coins       int not null default 0,
    hunger      int not null default 50,
    bond_score  int not null default 0,
    updated_at  timestamptz not null default now()
);

-- ── Pet Events ────────────────────────────────────────────────
create table if not exists public.pet_events (
    id          bigint generated by default as identity primary key,
    room_code   text not null references public.pet_rooms(room_code) on delete cascade,
    event_type  text not null,
    action_type text,
    actor_name  text not null default '队友',
    message     text,
    delta       jsonb not null default '{}'::jsonb,
    created_at  timestamptz not null default now()
);

-- ── Indexes ────────────────────────────────────────────────────
create index if not exists idx_pet_events_room_code_created_at
    on public.pet_events(room_code, created_at desc);

-- ── RLS (启用后 anon key 才能访问) ──────────────────────────────
alter table public.pet_rooms enable row level security;
alter table public.cloud_pets enable row level security;
alter table public.pet_events enable row level security;

-- 允许所有人读取/插入/更新（第一版简化）
create policy "Allow all on pet_rooms"
    on public.pet_rooms for all
    using (true)
    with check (true);

create policy "Allow all on cloud_pets"
    on public.cloud_pets for all
    using (true)
    with check (true);

create policy "Allow all on pet_events"
    on public.pet_events for all
    using (true)
    with check (true);
